### ISSUE TITLE
Failed to download chart for cs-k8s-protection-agent-0.917.0.tgz

### ISSUE THREAD

**Issue by jordanduttinger** [CrowdStrike/terraform-kubectl-falcon#22]
module version 0.2.0
Terraform v1.1.0
Unable to deploy the k8s-protection-agent.

```
╷
│ Error: could not download chart: failed to download "https://registry.crowdstrike.com/kpagent-helm/cs-k8s-protection-agent-0.917.0.tgz"
│ 
│   with module.falcon_k8s-protection-agent[0].helm_release.kpagent,
│   on .terraform/modules/falcon_k8s-protection-agent/modules/k8s-protection-agent/main.tf line 1, in resource "helm_release" "kpagent":
│    1: resource "helm_release" "kpagent" {
│ 
╵
```

Not sure what to do to resolve this.
I'm able to curl it no problem, but every time I try to apply the creation fails with above error

**Comment by ffalor** [comment]
Hey, what version of the helm provider are you using?

**Comment by jordanduttinger** [comment]
Using helm provider version 2.8.0
Thanks for the `HELM_DEBUG=1` suggestion it lead to seeing more useful error messages mainly an empty index.yaml after some tinkering with helm repos I was able to get it to deploy so you can probably close this issue because it seems it was an issue with my local helm configuration.

**Comment by ffalor** [comment]
Awesome! glad you were able to figure out the issue. If you think it's an issue others may run into and if you are are willing, adding a comment describing your fix might help others down the road.
