### ISSUE TITLE
correct way to install k8s-protection-agent if falcon-sensor is already running?

### ISSUE THREAD

**Issue by tiwari3010** [CrowdStrike/terraform-kubectl-falcon#25]
Hi Team,

   I have EKS cluster running with Falcon-sensor as side car. When any other app is getting deployed I am able to pass the secret (falcon sensor image is stored in private repository) to the app and when deploying the app its able to pull the image successfully and build. 

But when k8s-protection-agent getting installed after  falcon-sensor is already installed its not able to pull the falcon-sensor image using the same secret used for other apps. 

I tried below code in terraform but its not working:

```ruby
resource "helm_release" "kpagent" {
  name             = "kpagent"
  chart            = "cs-k8s-protection-agent"
  repository       = "https://registry.crowdstrike.com/kpagent-helm"
  namespace        = "falcon-kubernetes-protection"
  create_namespace = true
  reset_values     = true

  values = [
    yamlencode({
      imagePullSecrets = [
        {
          name      = "falcon-kubernetes-protection-registry-secret"
          namespace = "falcon-kubernetes-protection"
        }
      ]
    })
  ]  

  set {
    name  = "crowdstrikeConfig.clientID"
    value = var.falcon_client_id
  }

  set {
    name  = "crowdstrikeConfig.clientSecret"
    value = var.falcon_clientSecret
  }

  set {
    name  = "crowdstrikeConfig.clusterName"
    value = "${var.cluster_name}_${var.environment}"
  }

  set {
    name  = "crowdstrikeConfig.env"
    value = "us-1"
  }

  set {
    name  = "crowdstrikeConfig.cid"
    value = var.cid
  }

  set {
    name  = "crowdstrikeConfig.dockerAPIToken"
    value = var.dockerAPIToken
  }
  depends_on = [aws_eks_cluster.eks_cluster, aws_eks_fargate_profile.eks_fargate, aws_eks_fargate_profile.eks_fargate_logging, helm_release.falcon_helm]
}
```

what is the correct way to install k8s-protection-agent, if falcon-sensor is already running?

**Comment by ffalor** [comment]
I'm sorry I do not know the answer to that question. I'd suggest reaching out to support. They will be able to answer or route you to the correct answer.

On a separate note, is there something from the module that you want/need that is missing?

**Comment by brieschick34** [comment]
> Hi @ffalor, I wrote this code but got the idea from this module. My question is not regarding the module. I am asking this question in general. How to install/re-install k8s-protection-agent if falcon-sensor container is already running?

Hey I solved this for my org. I also had a call with crowdstrike to let them know they need to add a variable to the terraform to toggle the module for the orchestrator off and on so you can just get the KPA part. Till they do that you can just reference that KPA submodule in the repo like this:

```
module "crowdstrike_falcon_kpa" {
  source = "git::https://github.com/CrowdStrike/terraform-kubectl-falcon.git//modules//k8s-protection-agent"

  cluster_name     = var.cluster_name
  cloud            = var.cloud
  client_id        = var.client_id
  cid              = var.cid
  client_secret    = var.client_secret
  docker_api_token = var.docker_api_token
}
```

**Comment by ffalor** [comment]
@brieschick34 I originally misunderstood your question. Sorry for the confusion.

Like you said, if you only want kpa then you can use the submodule to do the install.

The root module `falcon` is meant to always install both KPA and Operator. Operator & KPA were added as submodules to allow you to install them individually.

``` terraform
module "falcon_k8s-protection-agent" {
  source  = "CrowdStrike/falcon/kubectl//modules/k8s-protection-agent"
  version = "0.3.0"
  # insert the 6 required variables here
}
```
