### ISSUE TITLE
destroy operation does not delete sensor from k8s cluster

### ISSUE THREAD

**Issue by ryanjpayne** [CrowdStrike/terraform-kubectl-falcon#28]
terraform destroy will successfully delete the falcon operator but leaves the falcon sensor on the cluster, requiring a manual kubectl delete to achieve the desired result.

**Comment by ffalor** [comment]
That's something the operator doesn't do. I'm down to do it in the Terraform module because it makes sense.

**Comment by ryanjpayne** [comment]
Yes I agree the module should be able to execute all terraform operations, including destroy, against any infrastructure managed in its configuration

**Comment by znedw** [comment]
Hi, is there a way to switch off the local-exec provisioner? When we destroy, we don't have a valid kubeconfig so this step always fails, we're deleting the cluster so it's not an issue. It would be great to be able to opt-out from this step...

**Comment by ffalor** [comment]
@znedw i've merged your code change and released a new version of the module `v0.5.0` that should solve your issue. Thanks again for contributing.
