### ISSUE TITLE
Enable configuring serviceAccount annotations to be able to use AWS IAM

### ISSUE THREAD

**Issue by db-er** [CrowdStrike/terraform-kubectl-falcon#33]
Hello, I am working with Crowdstrike support on an issue, and their troubleshooting steps have me follow these directions:

https://github.com/CrowdStrike/falcon-operator/blob/main/docs/deployment/eks-fargate/README.md#configuring-iam-role-to-allow-ecr-access-on-eks-fargate

Basically, you need to add to the FalconSensor deployment:

  injector:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::12345678910:role/eksctl-demo-cluster-addon-iamservic-Role1-J78KUNY32R1

However, this module does not appear to offer any way to add this to the FalconSensor deployment.

Here is my module code:

module "crowdstrike_falcon" {
  source = "CrowdStrike/falcon/kubectl"
  version = "0.3.0"

  cid              = local.secrets["cid"]
  client_id        = local.secrets["client_id"]
  client_secret    = local.secrets["client_secret"]
  cloud            = "us-2"
  cluster_name     = local.cluster_name
  docker_api_token = local.secrets["docker_api_token"]
  sensor_type      = "FalconContainer"
}

**Comment by redhatrises** [comment]
All settings are  now supported through custom manifest files as of v.0.4.0
